apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  DBUSERNAME: ""
  PASSWORD: ""
  

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-cm 
data:
  Age: "23"
  DBUSERNAME: "admin"
  PASSWORD: "MYSQL"
  API_TOKEN: "12345"